2025-05-09 22:22:11,839 INFO    MainThread:3853648 [wandb_setup.py:_flush():68] Current SDK version is 0.19.10
2025-05-09 22:22:11,839 INFO    MainThread:3853648 [wandb_setup.py:_flush():68] Configure stats pid to 3853648
2025-05-09 22:22:11,839 INFO    MainThread:3853648 [wandb_setup.py:_flush():68] Loading settings from /home/jchang13/.config/wandb/settings
2025-05-09 22:22:11,839 INFO    MainThread:3853648 [wandb_setup.py:_flush():68] Loading settings from /home/jchang13/fusion/mmegogesture-fusion/wandb/settings
2025-05-09 22:22:11,840 INFO    MainThread:3853648 [wandb_setup.py:_flush():68] Loading settings from environment variables
2025-05-09 22:22:11,840 INFO    MainThread:3853648 [wandb_init.py:setup_run_log_directory():724] Logging user logs to /home/jchang13/fusion/mmegogesture-fusion/wandb/run-20250509_222211-4848e8cv/logs/debug.log
2025-05-09 22:22:11,841 INFO    MainThread:3853648 [wandb_init.py:setup_run_log_directory():725] Logging internal logs to /home/jchang13/fusion/mmegogesture-fusion/wandb/run-20250509_222211-4848e8cv/logs/debug-internal.log
2025-05-09 22:22:11,841 INFO    MainThread:3853648 [wandb_init.py:init():852] calling init triggers
2025-05-09 22:22:11,842 INFO    MainThread:3853648 [wandb_init.py:init():857] wandb.init called with sweep_config: {}
config: {'fusion': {'fusion_level': 'multi', 'fusion_mode': 'cross'}, 'project': 'gesture_attention', 'sensor': {'select': ['rad-uD', 'cam-img'], 'win_cam': 80, 'win_rad': 512, 't_snapshot': 2.667, 'fps_cam': 30}, 'preprocess': {'flag_statistics': True, 'flag_visualize': False}, 'train': {'learning_rate': 0.0001, 'weight_decay': 0.01, 'epoch': 100, 'batch_size': 16, 'num_workers': 4, 'delta': 0.01, 'traintest_split': 'subject-3_4_5', 'n_class': 12, 'pretrain': True}, 'model': {'backbone': 'mobilenet-2D', 'fusion': 'multi_cross'}, 'wandb': {'use_wandb': True, 'log_all': False, 'project': 'Gesture_attention'}, 'transforms': {'t_actual': 1.6, 't_spare': 0.2, 'resample_cam': 16, 'cropratio_uD': 1.0, 'size_rad_D': 256, 'size_rad_T': 512, 'size_cam': 256, 'mean_std': {'rad-uD': [8.209, 6.3781], 'rad-uD_Whalf': [11.5463, 6.8219], 'rad-uD_Wdouble': [5.0373, 6.2107], 'rad-A': [40.2172, 7.3238], 'rad-R': [52.2055, 4.7976], 'rad-D': [46.6549, 23.3134], 'rad-uD_channel': [7.6703, 7.2454], 'cam-img': [[0.4125, 0.1556], [0.4229, 0.149], [0.4251, 0.1561]], 'cam-vid': [[0.4125, 0.1556], [0.4229, 0.149], [0.4251, 0.1561]]}}, 'result': {'save_vis': False, 'save_model': False, 'path_data': '/bigdata/shuboy/mm-egogesture/Gesture_processed_public', 'path_des': '/home/jchang13/fusion/mmegogesture-fusion/downloads/Metadata/des_public.csv', 'path_save_vis': '/home/jchang13/fusion/mmegogesture-fusion/vis_outputs', 'name': 'jchang-gesture_attention-epoch100', 'note': 'Temp', 'labels': ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12'], 'classes': ['06.Click', '05.FSnap', '04.ZIn', '07.Knock', '08.SwpL', '09.SwpR', '10.T_ZIn', '11.T_ZOut', '12.Stop', '01.OK', '03.TmbUp', '02.Photo']}, '_wandb': {}}
2025-05-09 22:22:11,842 INFO    MainThread:3853648 [wandb_init.py:init():893] starting backend
2025-05-09 22:22:11,842 INFO    MainThread:3853648 [wandb_init.py:init():897] sending inform_init request
2025-05-09 22:22:11,848 INFO    MainThread:3853648 [backend.py:_multiprocessing_setup():101] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2025-05-09 22:22:11,848 INFO    MainThread:3853648 [wandb_init.py:init():907] backend started and connected
2025-05-09 22:22:11,855 INFO    MainThread:3853648 [wandb_init.py:init():1002] updated telemetry
2025-05-09 22:22:11,877 INFO    MainThread:3853648 [wandb_init.py:init():1026] communicating run to backend with 90.0 second timeout
2025-05-09 22:22:12,318 INFO    MainThread:3853648 [wandb_init.py:init():1101] starting run threads in backend
2025-05-09 22:22:12,650 INFO    MainThread:3853648 [wandb_run.py:_console_start():2566] atexit reg
2025-05-09 22:22:12,650 INFO    MainThread:3853648 [wandb_run.py:_redirect():2414] redirect: wrap_raw
2025-05-09 22:22:12,651 INFO    MainThread:3853648 [wandb_run.py:_redirect():2483] Wrapping output streams.
2025-05-09 22:22:12,651 INFO    MainThread:3853648 [wandb_run.py:_redirect():2506] Redirects installed.
2025-05-09 22:22:12,657 INFO    MainThread:3853648 [wandb_init.py:init():1147] run started, returning control to user process
2025-05-09 22:25:01,797 INFO    MsgRouterThr:3853648 [mailbox.py:close():129] [no run ID] Closing mailbox, abandoning 1 handles.
2025-05-09 22:25:01,962 ERROR   MainThread:3853648 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2493, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 464, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1632, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 763, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-05-09 22:25:01,972 ERROR   MainThread:3853648 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2493, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 464, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1632, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 763, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-05-09 22:25:01,973 ERROR   MainThread:3853648 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2493, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 464, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1632, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 763, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-05-09 22:25:01,974 ERROR   MainThread:3853648 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2493, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 464, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1632, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 763, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-05-09 22:25:01,975 ERROR   MainThread:3853648 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2493, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 464, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1632, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 763, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-05-09 22:25:01,976 ERROR   MainThread:3853648 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2493, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 464, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1632, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 763, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-05-09 22:25:01,977 ERROR   MainThread:3853648 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2493, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 464, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1632, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 763, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-05-09 22:25:01,977 ERROR   MainThread:3853648 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2493, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 464, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1632, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 763, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-05-09 22:25:01,978 ERROR   MainThread:3853648 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2493, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 464, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1632, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 763, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-05-09 22:25:01,979 ERROR   MainThread:3853648 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2493, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 464, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1632, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 763, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-05-09 22:25:01,979 ERROR   MainThread:3853648 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2493, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 464, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1632, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 763, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-05-09 22:25:01,980 ERROR   MainThread:3853648 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2493, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 464, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1632, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 763, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-05-09 22:25:01,981 ERROR   MainThread:3853648 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2493, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 464, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1632, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 763, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-05-09 22:25:01,983 ERROR   MainThread:3853648 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2493, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 464, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1632, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 763, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-05-09 22:25:01,983 ERROR   MainThread:3853648 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2493, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 464, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1632, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 763, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-05-09 22:25:01,983 ERROR   MainThread:3853648 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2493, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 464, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1632, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 763, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-05-09 22:25:01,984 ERROR   MainThread:3853648 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2493, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 464, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1632, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 763, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-05-09 22:25:02,011 ERROR   MainThread:3853648 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2493, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 464, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1632, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 763, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-05-09 22:25:02,011 ERROR   MainThread:3853648 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2493, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 464, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1632, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 763, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-05-09 22:25:02,012 ERROR   MainThread:3853648 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2493, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 464, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1632, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 763, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-05-09 22:25:02,012 ERROR   MainThread:3853648 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2493, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 464, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1632, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 763, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-05-09 22:25:02,014 ERROR   MainThread:3853648 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2493, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 464, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1632, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 763, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-05-09 22:25:02,015 ERROR   MainThread:3853648 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2493, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 464, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1632, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 763, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-05-09 22:25:02,015 ERROR   MainThread:3853648 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2493, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 464, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1632, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 763, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-05-09 22:25:02,016 ERROR   MainThread:3853648 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2493, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 464, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1632, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 763, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-05-09 22:25:02,016 ERROR   MainThread:3853648 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2493, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 464, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1632, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 763, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-05-09 22:25:02,017 ERROR   MainThread:3853648 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2493, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 464, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1632, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 763, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-05-09 22:25:02,018 ERROR   MainThread:3853648 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2493, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 464, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1632, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 763, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-05-09 22:25:02,082 ERROR   MainThread:3853648 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2493, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 464, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1632, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 763, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-05-09 22:25:02,082 ERROR   MainThread:3853648 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2493, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 464, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1632, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 763, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-05-09 22:25:02,082 ERROR   MainThread:3853648 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2493, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 464, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1632, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 763, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-05-09 22:25:02,083 ERROR   MainThread:3853648 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2493, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 464, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1632, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 763, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-05-09 22:25:02,084 ERROR   MainThread:3853648 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2493, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 464, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1632, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 763, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-05-09 22:25:02,085 ERROR   MainThread:3853648 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2493, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 464, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1632, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 763, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-05-09 22:25:02,100 ERROR   MainThread:3853648 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2493, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 464, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1632, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 763, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-05-09 22:25:02,100 ERROR   MainThread:3853648 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2493, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 464, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1632, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 763, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-05-09 22:25:02,101 ERROR   MainThread:3853648 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2493, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 464, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1632, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 763, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-05-09 22:25:02,101 ERROR   MainThread:3853648 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2493, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 464, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1632, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 763, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-05-09 22:25:02,103 ERROR   MainThread:3853648 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2493, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 464, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1632, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 763, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-05-09 22:25:02,104 ERROR   MainThread:3853648 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2493, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 464, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1632, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 763, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-05-09 22:25:02,104 ERROR   MainThread:3853648 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2493, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 464, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1632, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 763, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-05-09 22:25:02,104 ERROR   MainThread:3853648 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2493, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 464, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1632, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 763, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-05-09 22:25:02,116 ERROR   MainThread:3853648 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2493, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 464, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1632, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 763, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-05-09 22:25:02,116 ERROR   MainThread:3853648 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2493, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 464, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1632, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 763, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-05-09 22:25:02,117 ERROR   MainThread:3853648 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2493, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 464, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1632, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 763, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-05-09 22:25:02,118 ERROR   MainThread:3853648 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2493, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 464, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1632, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 763, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-05-09 22:25:02,119 ERROR   MainThread:3853648 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2493, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 464, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1632, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 763, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-05-09 22:25:02,120 ERROR   MainThread:3853648 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2493, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 464, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1632, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 763, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-05-09 22:25:02,120 ERROR   MainThread:3853648 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2493, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 464, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1632, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 763, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-05-09 22:25:02,121 ERROR   MainThread:3853648 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2493, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 464, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1632, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 763, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-05-09 22:25:02,121 ERROR   MainThread:3853648 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2493, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 464, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1632, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 763, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-05-09 22:25:02,121 ERROR   MainThread:3853648 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2493, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 464, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1632, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 763, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-05-09 22:25:02,122 ERROR   MainThread:3853648 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2493, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 464, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1632, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 763, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/jchang13/miniconda3/envs/mmegogesture/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
